image: docker:latest

services:
- docker:dind

stages:
- build
- test
- release
- deploy

variables:
  CONTAINER_TEST_IMAGE: quay.io/colindensem/hello-rancher:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: quay.io/colindensem/hello-rancher:latest
  DOCKER_DRIVER: overlay2


# before_script:
  # - docker login -u $CI_JOB_USER -p $CI_JOB_PASS quay.io
  # - docker info


build:
  stage: build

  script:
    - docker login -u $CI_JOB_USER -p $CI_JOB_PASS quay.io
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

test1:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run $CONTAINER_TEST_IMAGE rake test

release-image:
  stage: release
  script:
    - docker login -u $CI_JOB_USER -p $CI_JOB_PASS quay.io
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --stack default --service sinatra
